project:
  type: website
  output-dir: docs

website:
  title: "Landon's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Hobbies.qmd  
        text: Hobbies

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



